Basic Anti-Bot Protection
CodeForcer/localcoinbot pull request #2
Opened 2021-01-29 11:06 UTC by Gingerbreadfork

1.) Simple colored shapes have been used on buttons that shuffle and require a new user to select the "green circle" this allows those that don't speak English or happen to be color blind to complete the entry test. If a user fails they are simply restricted from posting which should reduce the issues with accidental failures as they can contact an admin they see in the chat.

2.) Welcome message has also been adjusted to avoid rollover on mobile.

3.) Was unable to find a way to time delete the messages, but showing the link preview on the message has been disabled to avoid it being too large (suggestions on how to remove the messages after a set amount of time would be great if you have any ideas I hit a wall trying to get this to work).

![image](https://user-images.githubusercontent.com/42175382/106267532-e6f23880-627d-11eb-84b5-49b38feb82eb.png)

2021-02-01 18:00 UTC, CodeForcer requested changes
I think this is great, only thing missing is the message delete functionality. I think we need that or we are going to be annoying people in the chat.

It will be great to drop that annoying welcome message that plays every 3 joiners

2021-02-01 18:00 UTC, CodeForcer commented on localcoinbot.py
> +    updater = Updater(str(TOKEN), use_context=True)
@Gingerbreadfork was this due to the update of the package? Generally we try and avoid too much casting in Python for readability. Only a miner issue though

2021-02-01 18:00 UTC, CodeForcer commented on localcoinbot.py
> +            context.bot.sendMessage(
@Gingerbreadfork what does this return? Maybe the message ID?

2021-02-01 18:15 UTC, Gingerbreadfork commented on localcoinbot.py
> +    updater = Updater(str(TOKEN), use_context=True)
use_context param here is required for v12 of the python-telegram-bot package but won't be required for v13, just some of the magic of this package apparently.

2021-02-09 11:43 UTC, CodeForcer approved these changes
Happy to merge, looks good

2021-02-09 11:44 UTC, merged